import 'package:dayfi/services/api/database_service.dart';
import 'package:dayfi/data/storage/secure_storage_service.dart';
import 'package:dayfi/ui/bottom_sheets/notice/notice_sheet.dart';
import 'package:dayfi/ui/dialogs/info_alert/info_alert_dialog.dart';
import 'package:dayfi/ui/views/home/home_view.dart';
import 'package:dayfi/ui/views/startup/startup_view.dart';
import 'package:stacked/stacked_annotations.dart';
import 'package:stacked_services/stacked_services.dart';
import 'package:dayfi/ui/views/signup/signup_view.dart';
import 'package:dayfi/ui/views/login/login_view.dart';
import 'package:dayfi/ui/views/forgot_password/forgot_password_view.dart';
import 'package:dayfi/ui/views/verify_email/verify_email_view.dart';
import 'package:dayfi/ui/views/reset_password/reset_password_view.dart';
import 'package:dayfi/ui/views/success/success_view.dart';
import 'package:dayfi/ui/views/main/main_view.dart';
import 'package:dayfi/ui/views/settings/settings_view.dart';
import 'package:dayfi/ui/views/profile/profile_view.dart';
import 'package:dayfi/ui/views/transaction_pin_set/transaction_pin_set_view.dart';
import 'package:dayfi/ui/views/transaction_pin_change/transaction_pin_change_view.dart';
import 'package:dayfi/ui/views/password_change/password_change_view.dart';
import 'package:dayfi/ui/views/coins/coins_view.dart';
import 'package:dayfi/ui/views/verify_phone/verify_phone_view.dart';
import 'package:dayfi/ui/views/level_one_part_a/level_one_part_a_view.dart';
import 'package:dayfi/ui/views/level_one_part_b/level_one_part_b_view.dart';
import 'package:dayfi/ui/views/coin_detail/coin_detail_view.dart';
import 'package:dayfi/ui/views/wallets/wallets_view.dart';
import 'package:dayfi/ui/views/kyc_levels/kyc_levels_view.dart';
import 'package:dayfi/ui/views/swap/swap_view.dart';
import 'package:dayfi/ui/views/payment_setup/payment_setup_view.dart';
import 'package:dayfi/ui/views/add_funds/add_funds_view.dart';
import 'package:dayfi/ui/views/add_funds_options/add_funds_options_view.dart';
import 'package:dayfi/ui/views/send_funds/send_funds_view.dart';
import 'package:dayfi/ui/views/send_funds_options/send_funds_options_view.dart';
import 'package:dayfi/ui/views/passcode/passcode_view.dart';
import 'package:dayfi/ui/views/create_passcode/create_passcode_view.dart';
import 'package:dayfi/ui/views/reenter_passcode/reenter_passcode_view.dart';
import 'package:dayfi/ui/views/linked_banks/linked_banks_view.dart';
import 'package:dayfi/ui/views/link_a_bank/link_a_bank_view.dart';
import 'package:dayfi/ui/views/kyc_success/kyc_success_view.dart';
import 'package:dayfi/ui/views/cards/cards_view.dart';
import 'package:dayfi/ui/views/prepaid_info/prepaid_info_view.dart';
import 'package:dayfi/ui/views/personalise_card/personalise_card_view.dart';
import 'package:dayfi/ui/views/tranfers_details_selection/tranfers_details_selection_view.dart';
import 'package:dayfi/ui/views/recipient_details/recipient_details_view.dart';
import 'package:dayfi/ui/views/amount_entry/amount_entry_view.dart';
import 'package:dayfi/ui/views/transaction_pin_new/transaction_pin_new_view.dart';
import 'package:dayfi/ui/views/transaction_pin_confirm/transaction_pin_confirm_view.dart';
import 'package:dayfi/ui/views/wallet_details/wallet_details_view.dart';
import 'package:dayfi/ui/views/transaction_details/transaction_details_view.dart';
import 'package:dayfi/ui/views/wallet/wallet_view.dart';
import 'package:dayfi/ui/views/blog/blog_view.dart';
import 'package:dayfi/ui/views/blog_detail/blog_detail_view.dart';
import 'package:dayfi/ui/views/faqs/faqs_view.dart';
import 'package:dayfi/ui/views/transaction_history/transaction_history_view.dart';
import 'package:dayfi/ui/views/digital_dollar/digital_dollar_view.dart';
import 'package:dayfi/ui/views/wallet_address_info/wallet_address_info_view.dart';
import 'package:dayfi/ui/views/virtual_card_details/virtual_card_details_view.dart';
// @stacked-import

@StackedApp(
  routes: [
    MaterialRoute(page: HomeView),
    MaterialRoute(page: StartupView),
    MaterialRoute(page: SignupView),
    MaterialRoute(page: LoginView),
    MaterialRoute(page: ForgotPasswordView),
    MaterialRoute(page: VerifyEmailView),
    MaterialRoute(page: ResetPasswordView),
    MaterialRoute(page: SuccessView),
    MaterialRoute(page: MainView),
    MaterialRoute(page: SettingsView),
    MaterialRoute(page: ProfileView),
    MaterialRoute(page: TransactionPinSetView),
    MaterialRoute(page: TransactionPinChangeView),
    MaterialRoute(page: PasswordChangeView),
    MaterialRoute(page: CoinsView),
    MaterialRoute(page: VerifyPhoneView),
    MaterialRoute(page: LevelOnePartAView),
    MaterialRoute(page: LevelOnePartBView),
    MaterialRoute(page: CoinDetailView),
    MaterialRoute(page: WalletsView),
    MaterialRoute(page: KycLevelsView),
    MaterialRoute(page: SwapView),
    MaterialRoute(page: PaymentSetupView),
    MaterialRoute(page: AddFundsView),
    MaterialRoute(page: AddFundsOptionsView),
    MaterialRoute(page: SendFundsView),
    MaterialRoute(page: SendFundsOptionsView),
    MaterialRoute(page: PasscodeView),
    MaterialRoute(page: CreatePasscodeView),
    MaterialRoute(page: ReenterPasscodeView),
    MaterialRoute(page: LinkedBanksView),
    MaterialRoute(page: LinkABankView),
    MaterialRoute(page: KycSuccessView),
    MaterialRoute(page: CardsView),
    MaterialRoute(page: PrepaidInfoView),
    MaterialRoute(page: PersonaliseCardView),
    MaterialRoute(page: TransfersDetailsSelectionView),
    MaterialRoute(page: RecipientDetailsView),
    MaterialRoute(page: AmountEntryView),
    MaterialRoute(page: TransactionPinNewView),
    MaterialRoute(page: TransactionPinConfirmView),
    MaterialRoute(page: WalletDetailsView),
    MaterialRoute(page: TransactionDetailsView),
    MaterialRoute(page: WalletView),
    MaterialRoute(page: BlogView),
    MaterialRoute(page: BlogDetailView),
    MaterialRoute(page: FaqsView),
    MaterialRoute(page: TransactionHistoryView),
    MaterialRoute(page: DigitalDollarView),
    MaterialRoute(page: WalletAddressInfoView),
    MaterialRoute(page: VirtualCardDetailsView),
// @stacked-route
  ],
  dependencies: [
    LazySingleton(classType: BottomSheetService),
    LazySingleton(classType: DialogService),
    LazySingleton(classType: NavigationService),
    LazySingleton(classType: SecureStorageService),
    LazySingleton(classType: DatabaseService)
    // @stacked-service
  ],
  bottomsheets: [
    StackedBottomsheet(classType: NoticeSheet),
    // @stacked-bottom-sheet
  ],
  dialogs: [
    StackedDialog(classType: InfoAlertDialog),
    // @stacked-dialog
  ],
)
class App {}
