plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
    id("com.google.gms.google-services")

}

android {
        signingConfigs {
            create("release") {
                val keystore = file("/Users/mac/my-release-key.jks")
                if (keystore.exists()) {
                    storeFile = keystore
                    storePassword = "unicorn77"
                    keyAlias = "my-key-alias"
                    keyPassword = "unicorn77"
                }
            }
        }
    namespace = "com.dayfi.app"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
        isCoreLibraryDesugaringEnabled = true
    }

    defaultConfig {
        // Application ID will be set by product flavors (dev, pilot, prod)
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion  // Minimum SDK for biometric support
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    buildTypes {
        release {
            val releaseKeystore = signingConfigs.getByName("release").storeFile
            signingConfig = if (releaseKeystore != null && releaseKeystore.exists()) {
                signingConfigs.getByName("release")
            } else {
                signingConfigs.getByName("debug")
            }
        }
    }

    packaging {
        resources {
            excludes += "/META-INF/versions/9/OSGI-INF/MANIFEST.MF"
        }
    }
}

flutter {
    source = "../.."
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11)
    }
}

dependencies {
  // Core library desugaring
  coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.0.4")

  // Import the Firebase BoM
  implementation(platform("com.google.firebase:firebase-bom:34.2.0"))

  // TODO: Add the dependencies for Firebase products you want to use
  // When using the BoM, don't specify versions in Firebase dependencies
  implementation("com.google.firebase:firebase-analytics")

  // Intercom SDK — pinned (avoid latest.release + match intercom_flutter)
  implementation("io.intercom.android:intercom-sdk:17.1.1")
  implementation("com.google.firebase:firebase-messaging:23.1.2")

  // Add the dependencies for any other desired Firebase products
  // https://firebase.google.com/docs/android/setup#available-libraries
}
// ----- BEGIN flavorDimensions (autogenerated by flutter_flavorizr) -----
apply { from("flavorizr.gradle.kts") }
// ----- END flavorDimensions (autogenerated by flutter_flavorizr) -----